SELECT A.ID
,CASE WHEN B.SIZE=1 THEN 'CRITICAL'
WHEN B.SIZE=2 THEN 'HIGH' 
WHEN B.SIZE=3 THEN 'MEDIUM' 
WHEN B.SIZE=4 THEN 'LOW' 
END AS COLONY_NAME
FROM ECOLI_DATA AS A INNER JOIN 
(SELECT ID
,NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE
FROM ECOLI_DATA) AS B ON A.ID=B.ID
ORDER BY A.ID ASC;