SELECT PRODUCT_ID
,PRODUCT_NAME
,SUM(TOTAL_SALES) AS TOTAL_SALES 
FROM 
(SELECT A.PRODUCT_ID
,A.PRODUCT_NAME
,B.AMOUNT*A.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS A INNER JOIN FOOD_ORDER AS B 
ON A.PRODUCT_ID=B.PRODUCT_ID
WHERE B.PRODUCE_DATE LIKE '2022-05%') AS ITEMS
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC; 